export * from './test-page/test-page.component';
export * from './test-page/test-page.route';
export * from './about-page/about-page.component';
export * from './about-page/about-page.route';
export * from './about-project-page/about-project-page.component';
export * from './about-project-page/about-project-page.route';
export * from './home/home.component';
export * from './home.route';
export * from './home.module';
